management:
    endpoints:
        web:
            exposure:
                include: bus-refresh
spring:
    cloud:
        bus:
            enabled: true
            trace:
                enabled: true
    rabbitmq:
        host: 192.168.0.183
        password: guest
        port: 5672
        username: guest
